import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/colors';
import { Spacing } from '../../constants/spacing';

export const displayNameStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.foam,
    justifyContent: 'center',
    paddingHorizontal: Spacing.screenPadding,
  },
  wave1: {
    position: 'absolute',
    width: 300, height: 300,
    borderRadius: 150,
    backgroundColor: Colors.mist,
    opacity: 0.4,
    top: -80, right: -80,
  },
  wave2: {
    position: 'absolute',
    width: 200, height: 200,
    borderRadius: 100,
    backgroundColor: Colors.wave,
    opacity: 0.1,
    bottom: 60, left: -60,
  },
  dots: {
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    marginBottom: 32,
  },
  dot: {
    width: 7, height: 7,
    borderRadius: 4,
    backgroundColor: Colors.mist,
  },
  dotActive: {
    width: 20,
    backgroundColor: Colors.teal,
  },
  content: { width: '100%' },
  stepWrap: { alignItems: 'center' },
  bigEmoji: { fontSize: 56, marginBottom: 16 },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 22,
    color: Colors.textPrimary,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 8,
  },
  hint: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: '#9BB5C4',
    textAlign: 'center',
    marginBottom: 16,
  },
  input: {
    backgroundColor: Colors.surface,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.border,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm + 4,
    fontSize: 16,
    fontFamily: 'Nunito_400Regular',
    color: Colors.textPrimary,
    width: '100%',
    textAlign: 'center',
  },
  preview: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 13,
    color: Colors.teal,
    marginTop: 8,
  },

  pickerWrap: {
    width: 160,
    height: 200,
    overflow: 'hidden',
    position: 'relative',
    marginVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  pickerOverlayTop: {
    position: 'absolute',
    top: 0, left: 0, right: 0,
    height: 72,
    zIndex: 2,
    backgroundColor: Colors.surface,
    opacity: 0.75,
  },
  pickerOverlayBottom: {
    position: 'absolute',
    bottom: 0, left: 0, right: 0,
    height: 72,
    zIndex: 2,
    backgroundColor: Colors.surface,
    opacity: 0.75,
  },
  pickerSelector: {
    position: 'absolute',
    top: 72, left: 12, right: 12,
    height: 56,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: Colors.teal,
    borderRadius: 12,
    zIndex: 1,
  },
  pickerItem: {
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerSpacer: {
    height: 84,
  },
  pickerItemText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 20,
    color: Colors.muted,
  },
  pickerItemTextActive: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 26,
    color: Colors.teal,
  },
  manualInput: {
    width: 160,
    height: 200,
    backgroundColor: Colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: Spacing.md,
    fontSize: 42,
    fontFamily: 'Nunito_700Bold',
    color: Colors.teal,
    textAlign: 'center',
    textAlignVertical: 'center',
  },

  error: {
    color: Colors.alertHigh,
    fontSize: 13,
    fontFamily: 'Nunito_400Regular',
    textAlign: 'center',
    marginTop: 4,
  },
  btnPrimary: {
    backgroundColor: Colors.teal,
    borderRadius: 20,
    paddingVertical: 16,
    alignItems: 'center',
    width: '100%',
    marginTop: 24,
  },
  btnDisabled: { opacity: 0.45 },
  btnText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 15,
    color: Colors.textLight,
  },
  btnSkip: {
    marginTop: 12,
    padding: 6,
    alignSelf: 'center',
  },
  skipText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: '#9BB5C4',
    textDecorationLine: 'underline',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(12, 44, 58, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  modalCard: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: Colors.surface,
    borderRadius: 24,
    paddingVertical: 28,
    paddingHorizontal: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 24,
    elevation: 8,
  },
  modalEmoji: {
    fontSize: 48,
    marginBottom: 8,
  },
  modalTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 20,
    color: Colors.textPrimary,
    marginBottom: 6,
  },
  modalText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 20,
  },
  modalBtn: {
    backgroundColor: Colors.teal,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 32,
    width: '100%',
    alignItems: 'center',
  },
  modalBtnText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 15,
    color: Colors.textLight,
  },
});
