import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/colors';

export const trackerScreenStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 20,
  },
  headerTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 28,
    color: Colors.textPrimary,
    marginBottom: 4,
  },
  headerSub: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: Colors.textSecondary,
  },
  completedBadge: {
    backgroundColor: Colors.teal,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignItems: 'center',
  },
  completedText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 18,
    color: Colors.textLight,
  },
  completedLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 10,
    color: 'rgba(255,255,255,0.8)',
  },
  streakBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3E0',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 6,
    borderWidth: 1,
    borderColor: '#FFD59E',
  },
  streakBadgeCold: {
    backgroundColor: '#EEF4F8',
    borderColor: '#D6E4EE',
  },
  streakFlame: {
    fontSize: 18,
  },
  streakNum: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 18,
    color: '#E65100',
  },
  streakNumCold: {
    color: Colors.textSecondary,
  },
  streakLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 11,
    color: '#8B5A2B',
  },
  streakLabelCold: {
    color: Colors.textSecondary,
  },
  loadingIndicator: { marginTop: 60 },
  bottomSpacer: { height: 32 },
});

export const moodCalendarStyles = StyleSheet.create({
  card: {
    marginHorizontal: 24,
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 18,
    color: Colors.textPrimary,
    textTransform: 'capitalize',
  },
  countBadge: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 12,
    color: Colors.teal,
    backgroundColor: Colors.foam,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    overflow: 'hidden',
  },
  weekdayRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  weekdayCell: {
    flex: 1,
    alignItems: 'center',
  },
  weekdayText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 10,
    color: Colors.textSecondary,
    letterSpacing: 0.5,
  },
  weekRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  dayCell: {
    flex: 1,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 2,
    borderRadius: 10,
    backgroundColor: 'transparent',
    position: 'relative',
  },
  dayCellOutOfMonth: {
    opacity: 0.2,
  },
  dayCellFuture: {
    opacity: 0.35,
  },
  dayCellLogged: {
    backgroundColor: Colors.teal + '22',
  },
  dayCellToday: {
    borderWidth: 1.5,
    borderColor: Colors.teal,
  },
  dayCellSelected: {
    backgroundColor: Colors.teal,
  },
  dayNumber: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 13,
    color: Colors.textSecondary,
  },
  dayNumberLogged: {
    color: Colors.teal,
    fontFamily: 'Nunito_700Bold',
  },
  dayNumberSelected: {
    color: Colors.textLight,
    fontFamily: 'Nunito_700Bold',
  },
  loggedDot: {
    position: 'absolute',
    bottom: 4,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.teal,
  },
  loggedDotSelected: {
    backgroundColor: Colors.textLight,
  },
  activityPanel: {
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  activityTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 14,
    color: Colors.textPrimary,
    marginBottom: 10,
  },
  activityEmpty: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
    paddingVertical: 8,
  },
  activityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.foam,
    borderRadius: 12,
    padding: 12,
    gap: 12,
    marginBottom: 8,
  },
  activityEmoji: {
    fontSize: 26,
  },
  activityIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: Colors.teal + '22',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityIcon: {
    fontSize: 20,
  },
  activityBody: {
    flex: 1,
  },
  activityLabel: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 13,
    color: Colors.textPrimary,
    marginBottom: 2,
  },
  activitySub: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
  },
  activityChevron: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 20,
    color: Colors.textSecondary,
  },
});

export const moodLineChartStyles = StyleSheet.create({
  card: {
    marginHorizontal: 24,
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
  },
  header: {
    marginBottom: 12,
  },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: Colors.textPrimary,
    marginBottom: 2,
  },
  subtitle: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
  },
  toggle: {
    flexDirection: 'row',
    backgroundColor: Colors.foam,
    borderRadius: 10,
    padding: 3,
    marginTop: 12,
    marginBottom: 8,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: 'center',
  },
  toggleBtnActive: { backgroundColor: Colors.teal },
  toggleText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 11,
    color: Colors.textSecondary,
  },
  toggleTextActive: { color: Colors.textLight },
  chartWrap: {
    flexDirection: 'row',
    marginTop: 8,
  },
  yAxis: {
    width: 18,
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  yLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 9,
    color: Colors.textSecondary,
    textAlign: 'right',
  },
  plotWrap: {
    flex: 1,
    marginLeft: 6,
  },
  plot: {
    position: 'relative',
  },
  gridLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: Colors.border,
  },
  lineSegment: {
    position: 'absolute',
    backgroundColor: Colors.teal,
  },
  dot: {
    position: 'absolute',
    backgroundColor: Colors.teal,
    borderWidth: 2,
    borderColor: Colors.foam,
  },
  xAxisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  xLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 9,
    color: Colors.textSecondary,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  summaryItem: {
    alignItems: 'center',
    flex: 1,
  },
  summaryNum: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: Colors.textPrimary,
  },
  summaryLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 10,
    color: Colors.textSecondary,
    marginTop: 2,
    textAlign: 'center',
  },
  empty: {
    paddingVertical: 32,
    alignItems: 'center',
  },
  emptyText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
    textAlign: 'center',
  },
});

export const waterTrackerStyles = StyleSheet.create({
  card: {
    marginHorizontal: 24,
    marginTop: 20,
    backgroundColor: Colors.foam,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: Colors.textPrimary,
  },
  subtitle: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  mainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  counterBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.wave,
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterBtnDisabled: {
    backgroundColor: '#B8D9E3',
  },
  counterBtnText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 26,
    color: Colors.textLight,
    lineHeight: 30,
  },
  glassWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  glass: {
    width: 54,
    height: 72,
    borderLeftWidth: 3,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderTopWidth: 1.5,
    borderColor: Colors.teal,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    backgroundColor: Colors.foam,
  },
  glassFill: {
    width: '100%',
    backgroundColor: Colors.wave,
    opacity: 0.9,
  },
  glassCount: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 22,
    color: Colors.textPrimary,
    marginTop: 10,
  },
  glassCountGoal: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 16,
    color: Colors.textSecondary,
  },
  glassLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 11,
    color: Colors.textSecondary,
  },
  footerRow: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  footerText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
  },
  footerBold: {
    fontFamily: 'Nunito_700Bold',
    color: Colors.textPrimary,
  },
});

export const sleepTrackerStyles = StyleSheet.create({
  card: {
    marginHorizontal: 24,
    marginTop: 20,
    backgroundColor: Colors.foam,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: Colors.textPrimary,
  },
  subtitle: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  mainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  numberWrap: { flex: 1 },
  bigNumber: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 28,
    color: Colors.textPrimary,
  },
  unit: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
    marginTop: 4,
  },
  ringWrap: {
    width: 72,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringBg: {
    position: 'absolute',
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 8,
    borderColor: Colors.mist,
  },
  ringFill: {
    position: 'absolute',
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 8,
    borderColor: Colors.ocean,
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
  },
  ringPct: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 13,
    color: Colors.textPrimary,
  },
  emptyText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
    lineHeight: 18,
    paddingVertical: 8,
  },
  retryBtn: {
    marginTop: 10,
    alignSelf: 'flex-start',
    backgroundColor: Colors.teal,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  retryText: {
    fontFamily: 'Nunito_700Bold',
    color: Colors.textLight,
    fontSize: 13,
  },
  footerRow: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  footerText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
  },
  footerBold: {
    fontFamily: 'Nunito_700Bold',
    color: Colors.textPrimary,
  },
});

export const stepsTrackerStyles = StyleSheet.create({
  card: {
    marginHorizontal: 24,
    marginTop: 20,
    backgroundColor: Colors.foam,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: Colors.textPrimary,
  },
  subtitle: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  mainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  numberWrap: {
    flex: 1,
  },
  bigNumber: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 32,
    color: Colors.textPrimary,
  },
  unit: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  ringWrap: {
    width: 72,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringBg: {
    position: 'absolute',
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 8,
    borderColor: Colors.mist,
  },
  ringFill: {
    position: 'absolute',
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 8,
    borderColor: Colors.wave,
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
  },
  ringPct: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 13,
    color: Colors.textPrimary,
  },
  emptyText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
    lineHeight: 18,
    paddingVertical: 8,
  },
  retryBtn: {
    marginTop: 10,
    alignSelf: 'flex-start',
    backgroundColor: Colors.teal,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  retryText: {
    fontFamily: 'Nunito_700Bold',
    color: Colors.textLight,
    fontSize: 13,
  },
  footerRow: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  footerText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
  },
  footerBold: {
    fontFamily: 'Nunito_700Bold',
    color: Colors.textPrimary,
  },
});
